import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
const exoItalic = localFont({
  src: "./fonts/YesevaOne-Regular.ttf",
  variable: "--font-exo-italic",
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
     
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
